### ISSUE TITLE
build finishes, but no upload for osx

### ISSUE THREAD

**Issue by looooo** [conda-forge/pivy-feedstock#2]
@conda-forge/core
it seems like the build is working, but the upload does not:
~https://travis-ci.org/conda-forge/staged-recipes/builds/351407930#L1314L1316~
https://travis-ci.org/conda-forge/pivy-feedstock/jobs/355951038#L1143

edited link.

**Comment by jakirkham** [comment]
Seems to be there. What's the issue?

Should add uploading doesn't occur on `staged-recipes` only in the feedstock's CIs.

**Comment by looooo** [comment]
seems like I have mixed the links. now the link point to the correct build:
https://travis-ci.org/conda-forge/pivy-feedstock/jobs/355951038#L1143

**Comment by jakirkham** [comment]
Right. So still seeing the macOS packages in conda-forge. Screenshot below.

Feel like I'm missing something though. Please feel free to clarify.

<img width="1552" alt="screen shot 2018-03-21 at 04 50 26" src="https://user-images.githubusercontent.com/3019665/37700857-66e978b2-2cc3-11e8-9a73-16ad02afd399.png">

**Comment by looooo** [comment]
ah now I see my mistake. I was looking at the wrong conda-channel.... stupid me.
I need to make a brake. thanks for clarification.
